name: Build sstp-client for OpenWrt 24.10.2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip

    - name: Clone OpenWrt source (24.10.2)
      run: |
        git clone --single-branch --branch v24.10.2 https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        # Добавляем feeds
        ./scripts/feeds update -a
        ./scripts/feeds install sstp-client  # Устанавливаем пакет из feeds

    - name: Apply custom patch
      run: |
        cd openwrt
        # Предполагаем, что патч в корне репозитория как patches/sstp-client-custom.patch
        # Скачиваем ваш патч из checkout (actions/checkout уже сделал это)
        cp ../patches/300-increase-pppd-args-array-size.patch .
        # Применяем патч к пакету sstp-client
        cd feeds/packages/net/sstp-client/
        git apply ../../../300-increase-pppd-args-array-size.patch  # Адаптируйте путь

    - name: Configure for gl.inet AR750S
      run: |
        cd openwrt
        # Настраиваем .config для ramips/mt7621 (AR750S)
        make defconfig
        # Дополните .config (пример: добавьте CONFIG_PACKAGE_sstp-client=m в .config вручную или через make)
        echo 'CONFIG_PACKAGE_sstp-client=m' >> .config
        # Если нужно, настройте целевое устройство
        # make menuconfig (но в actions используйте скрипт для автоматизации)

    - name: Build sstp-client package
      run: |
        cd openwrt
        # Сборка только пакета sstp-client для econom (чтобы не собирать всю прошивку)
        make package/sstp-client/compile V=s  # V=s для verbose вывода, если нужно отладить

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sstp-client-opk
        path: openwrt/bin/packages/*/ramips/packages/*/sstp-client*.ipk
